services:
  mysql:
    image: mysql
    container_name: mysql-container
    restart: no
    environment:
      - MYSQL_DATABASE=MYSQL
      - MYSQL_USER=SA
      - MYSQL_PASSWORD=InsomniaRemix524!
      - MYSQL_ROOT_PASSWORD=InsomniaRemix524!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql-container
    restart: no
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=InsomniaRemix524!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/lib/mssql
volumes:
  mysql_data:
  mssql_data: