services:
  backend:
    container_name: spring-java-21-container
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mssql:
        condition: service_healthy
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0.45
    container_name: mysql-container
    restart: no
    environment:
      - MYSQL_DATABASE=MYSQL
      - MYSQL_USER=SA
      - MYSQL_PASSWORD=InsomniaRemix524!
      - MYSQL_ROOT_PASSWORD=InsomniaRemix524!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pInsomniaRemix524!" ]
      interval: 10s
      timeout: 5s
      retries: 10
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql-container
    restart: no
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "InsomniaRemix524!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'InsomniaRemix524!' -C" ]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
  mysql_data:
  mssql_data: