# DataSource MySQL
mysql.datasource.url=jdbc:mysql://mysql:3306/MYSQL?serverTimezone=America/Mexico_City
mysql.datasource.username=SA
mysql.datasource.password=InsomniaRemix524!
mysql.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA MySQL
mysql.jpa.hibernate.ddl-auto=update
mysql.jpa.database-platform=org.hibernate.dialect.MySQLDialect
mysql.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
mysql.jpa.generate-ddl=true
mysql.jpa.show-sql=true

# DataSource MSSQL
mssql.datasource.url=jdbc:sqlserver://mssql:1433;databaseName=MSSQL;encrypt=false;trustServerCertificate=true;
mssql.datasource.username=SA
mssql.datasource.password=InsomniaRemix524!
mssql.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
mssql.datasource.hikari.data-source-properties.authentication=ActiveDirectoryPassword

# JPA MSSQL
mssql.jpa.hibernate.ddl-auto=update
mssql.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
mssql.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
mssql.jpa.generate-ddl=true
mssql.jpa.show-sql=true

# Auth Keycloack
auth.base-url=https://dev-11513426.okta.com/oauth2/default
auth.keys-api=/v1/keys
auth.authorize-api=/v1/authorize
auth.token-api=/v1/token
auth.validate-api=/v1/introspect
auth.user-info-api=/v1/userinfo
auth.revoke-api=/v1/revoke
auth.logout-api=/v1/logout
auth.client-id=0oaocbbwxhaurUGdy5d7
auth.client-secret=WbbRuM8BSkJRhqyxy14ch43G6WhFLNtdOwozzIoTlnBoL4gPUSOnogacx2bUlxeU
auth.callback-redirect-uri=http://localhost:8080/api/auth/token
auth.logout-redirect-uri=http://localhost:8080/api/auth/login
auth.login-redirect-uri=http://localhost:3001/auth/login
auth.dashboard-redirect-uri=http://localhost:3001