# Auth Keycloack
auth.base-url=http://host.docker.internal:8090/realms/spring-java-21-realm
auth.keys-api=/protocol/openid-connect/certs
auth.authorize-api=/protocol/openid-connect/auth
auth.token-api=/protocol/openid-connect/token
auth.validate-api=/protocol/openid-connect/token/introspect
auth.user-info-api=/protocol/openid-connect/userinfo
auth.revoke-api=/protocol/openid-connect/revoke
auth.logout-api=/protocol/openid-connect/logout
auth.client-id=spring-java-21
auth.client-secret=z6RqCGOEljYpOrQF4jgvO3hqMC3dXk73
auth.callback-redirect-uri=http://localhost:8080/api/auth/token
auth.logout-redirect-uri=http://localhost:8080/api/auth/login
auth.login-redirect-uri=http://localhost:8080/api/auth/login
auth.dashboard-redirect-uri=http://localhost:8080/swagger-ui.html