swagger.security-scheme-name=cookieAuth
swagger.title=JosAnt
swagger.description=Demo Project
swagger.version=0.0.1

swagger.license.name=GNU GENERAL PUBLIC LICENSE 3.0
swagger.license.url=https://www.fsf.org

swagger.contact.name=JosAnt
swagger.contact.url=https://github.com/JosepAntonie
swagger.contact.email=insomniantonio@icloud.com